DROP TABLE IF EXISTS user_filmorate, film, mpa, genre, friend, like_for_film, genre_film CASCADE;

CREATE TABLE IF NOT EXISTS user_filmorate
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50) NOT NULL,
    login    varchar(50) NOT NULL,
    name     varchar(50),
    birthday date        NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50)  NOT NULL,
    description  varchar(200) NOT NULL,
    release_date date         NOT NULL,
    duration     integer      NOT NULL,
    mpa_id       integer      NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS friend
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_first_friend int NOT NULL,
    id_last_friend  int NOT NULL,
    FOREIGN KEY (id_first_friend) REFERENCES user_filmorate (id) ON DELETE CASCADE,
    FOREIGN KEY (id_last_friend) REFERENCES user_filmorate (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS like_for_film
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_film int NOT NULL,
    id_user int NOT NULL,
    FOREIGN KEY (id_film) REFERENCES film (id) ON DELETE CASCADE,
    FOREIGN KEY (id_user) REFERENCES user_filmorate (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre_film
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_film  int NOT NULL,
    id_genre int NOT NULL,
    FOREIGN KEY (id_film) REFERENCES film (id) ON DELETE CASCADE,
    FOREIGN KEY (id_genre) REFERENCES genre (id) ON DELETE CASCADE
);

